import {checkWorkDeadlines} from './workcards';
import {db,list} from './server';
import {namespace} from './context';
import {notifyUsers} from './web-push';
import {closed,statuses} from './domain';
export async function checkDeadlines(origin:string){const now=Date.now();const slot=Math.floor(now/30000);const lock=await db().prepare('INSERT OR IGNORE INTO records(id,kind,data,version) VALUES(?,?,?,0)').bind(namespace()+'deadline-tick:'+slot,namespace()+'deadline-ticks',String(now)).run();if(!lock.meta.changes)return 0;const [orders,users,equipment,areas]=await Promise.all(['orders','users','equipment','areas'].map(list));let created=await checkWorkDeadlines(origin);const recipients=new Set<string>();for(const o of orders.filter(o=>!closed(o))){const left=(Date.parse(o.due)-now)/60000,age=(now-Date.parse(o.created))/60000;const assigned=o.members||[o.worker];const targets:{kind:string,title:string,to:string[],body:string}[]=[];const name=(items:any[],id:string)=>items.find(x=>x.id===id)?.name||id;const context=`${name(equipment,o.equipment)} · ${name(areas,o.area)} · ${name(users,o.worker)} · ${statuses[o.status]}. ${o.lastComment||''}`;
if(left<=30&&left>0)targets.push({kind:'soon',title:`№${o.number}: до срока ${Math.ceil(left)} мин`,to:assigned,body:context});
if(left<=0)targets.push({kind:'late:'+Math.floor(-left/30),title:`№${o.number}: просрочка ${Math.ceil(-left)} мин`,to:[...assigned,o.master,...(left<=-120?users.filter(u=>u.role==='manager').map(u=>u.id):[])],body:context});
if(o.status==='issued'&&age>=(o.priority==='emergency'?3:10)){const free=users.find(w=>w.role==='worker'&&w.onShift&&!w.disabled&&w.id!==o.worker&&!orders.some(x=>!closed(x)&&x.status==='working'&&(x.worker===w.id||x.members?.includes(w.id))));targets.push({kind:'unaccepted',title:`№${o.number}: исполнитель не принял за ${Math.floor(age)} мин`,to:[o.master],body:context+(free?` Возможная замена: ${free.name} (${free.spec}). Мастер проверяет допуск.`:' Свободной замены нет.')});}
for(const a of targets){const id='alert:'+o.id+':'+a.kind;const record={id,order:o.id,title:a.title,text:a.body,to:[...new Set(a.to)],created:new Date(now).toISOString()};const result=await db().prepare('INSERT OR IGNORE INTO records(id,kind,data,version) VALUES(?,?,?,0)').bind(namespace()+id,namespace()+'alerts',JSON.stringify(record)).run();if(result.meta.changes){created++;record.to.forEach(x=>recipients.add(x));}}}
await notifyUsers([...recipients],origin).catch(()=>{});await db().prepare('DELETE FROM records WHERE kind=? AND CAST(data AS INTEGER)<?').bind(namespace()+'deadline-ticks',now-86400000).run();return created;}
